import type { GalleryProject } from './types';

/**
 * Fallback data galeri portofolio jika Supabase tidak tersedia / database kosong.
 */
export const MOCK_PROJECTS: GalleryProject[] = [
  {
    id: 'proj-1',
    title: 'Warm Sanctuary of Arya & Nadia',
    slug: 'arya-nadia-wedding',
    category: 'wedding',
    categoryLabel: 'Wedding',
    description: 'Perayaan pernikahan intim bernuansa budaya modern yang hangat di Danau Toba & Madura.',
    location: 'Toba Heritage Resort, North Sumatra',
    eventDate: '12 Mei 2026',
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1600&auto=format&fit=crop',
    isFeatured: true,
    images: [
      {
        id: 'img-1-1',
        projectId: 'proj-1',
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1600&auto=format&fit=crop',
        altText: 'Arya & Nadia Wedding Couple Portrait',
        sortOrder: 1,
        aspectRatio: 'landscape',
      },
      {
        id: 'img-1-2',
        projectId: 'proj-1',
        imageUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1600&auto=format&fit=crop',
        altText: 'Emotional Vow Moment',
        sortOrder: 2,
        aspectRatio: 'portrait',
      },
      {
        id: 'img-1-3',
        projectId: 'proj-1',
        imageUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=1600&auto=format&fit=crop',
        altText: 'Bride Aesthetic Preparation',
        sortOrder: 3,
        aspectRatio: 'portrait',
      },
      {
        id: 'img-1-4',
        projectId: 'proj-1',
        imageUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=1600&auto=format&fit=crop',
        altText: 'Evening Reception Glow',
        sortOrder: 4,
        aspectRatio: 'landscape',
      },
    ],
  },
  {
    id: 'proj-2',
    title: 'Poetry in Minimalist Light — Kevin & Clara',
    slug: 'kevin-clara-prewedding',
    category: 'pre-wedding',
    categoryLabel: 'Pre-Wedding',
    description: 'Sesi pre-wedding berkonsep arsitektural minimalis dengan fokus pada siluet dan kontras lembut.',
    location: 'Grand Ballroom & Modern Studio, Madura',
    eventDate: '28 April 2026',
    coverImage: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=1600&auto=format&fit=crop',
    isFeatured: true,
    images: [
      {
        id: 'img-2-1',
        projectId: 'proj-2',
        imageUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=1600&auto=format&fit=crop',
        altText: 'Kevin & Clara Studio Embrace',
        sortOrder: 1,
        aspectRatio: 'landscape',
      },
      {
        id: 'img-2-2',
        projectId: 'proj-2',
        imageUrl: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=1600&auto=format&fit=crop',
        altText: 'Sunset Contour',
        sortOrder: 2,
        aspectRatio: 'portrait',
      },
      {
        id: 'img-2-3',
        projectId: 'proj-2',
        imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1600&auto=format&fit=crop',
        altText: 'Close Up Emotional Detail',
        sortOrder: 3,
        aspectRatio: 'portrait',
      },
    ],
  },
  {
    id: 'proj-3',
    title: 'Reflections of Elegance — Sarah Persona',
    slug: 'sarah-persona-portrait',
    category: 'portrait',
    categoryLabel: 'Portrait',
    description: 'Eksplorasi estetika portrait editorial wanita dengan tone analog dramatis.',
    location: 'Sera Creative Studio, Madura',
    eventDate: '15 Maret 2026',
    coverImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1600&auto=format&fit=crop',
    isFeatured: true,
    images: [
      {
        id: 'img-3-1',
        projectId: 'proj-3',
        imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1600&auto=format&fit=crop',
        altText: 'Sarah Editorial Portrait',
        sortOrder: 1,
        aspectRatio: 'portrait',
      },
      {
        id: 'img-3-2',
        projectId: 'proj-3',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1600&auto=format&fit=crop',
        altText: 'Moody Soft Shadow Portrait',
        sortOrder: 2,
        aspectRatio: 'portrait',
      },
    ],
  },
  {
    id: 'proj-4',
    title: 'The Eternal Oath of Bima & Dian',
    slug: 'bima-dian-wedding',
    category: 'wedding',
    categoryLabel: 'Wedding',
    description: 'Pernikahan outdoor bergaya garden rustic dengan sentuhan kehangatan keluarga.',
    location: 'Jalan pamekasan',
    eventDate: '02 Februari 2026',
    coverImage: 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?q=80&w=1600&auto=format&fit=crop',
    isFeatured: false,
    images: [
      {
        id: 'img-4-1',
        projectId: 'proj-4',
        imageUrl: 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?q=80&w=1600&auto=format&fit=crop',
        altText: 'Bima & Dian Ring Exchange',
        sortOrder: 1,
        aspectRatio: 'landscape',
      },
    ],
  },
];
