import { Service, Package, GalleryProject, Availability, Booking } from './types';

export const MOCK_SERVICES: Service[] = [
  {
    id: 's-wedding',
    name: 'Wedding Photography',
    slug: 'wedding',
    description: 'Dokumentasi sinematik momen paling bermakna dalam hidup Anda dengan sentuhan editorial dan emosi yang timeless.',
    isActive: true,
  },
  {
    id: 's-prewedding',
    name: 'Pre-Wedding Story',
    slug: 'pre-wedding',
    description: 'Sesi foto intim berkonsep editorial di lokasi pilihan Anda untuk mengabadikan perjalanan cinta Anda.',
    isActive: true,
  },
  {
    id: 's-couple',
    name: 'Couple & Engagement',
    slug: 'couple',
    description: 'Potret romantis kasual nan elegan yang menangkap gestur dan kehangatan alami pasangan.',
    isActive: true,
  },
  {
    id: 's-portrait',
    name: 'Editorial & Portrait',
    slug: 'portrait',
    description: 'Sesi portrait personal & fashion dengan komposisi pencahayaan moody khas Marga Sera.',
    isActive: true,
  },
  {
    id: 's-graduation',
    name: 'Graduation Celebration',
    slug: 'graduation',
    description: 'Perayaan pencapaian akademis dengan dokumentasi penuh gaya bersama keluarga dan kerabat.',
    isActive: true,
  },
];

export const MOCK_PACKAGES: Package[] = [
  // Wedding Packages
  {
    id: 'pkg-w-basic',
    serviceId: 's-wedding',
    serviceName: 'Wedding Photography',
    name: 'Essence Wedding',
    slug: 'essence-wedding',
    description: 'Dokumentasi resepsi inti untuk momen pernikahan yang intim.',
    price: 8500000,
    duration: '6 Jam',
    photographerCount: 1,
    editedPhotos: '80 Foto Edited + All Raw',
    features: [
      '1 Main Photographer',
      'Dokumentasi s/d 6 Jam',
      '80 Tone Edited High-Res Photos',
      'All Raw Photos in Google Drive',
      'Exclusive Leather USB Flashdrive',
      '1 Frame Wooden 40x60 cm',
    ],
    isPopular: false,
    isActive: true,
  },
  {
    id: 'pkg-w-signature',
    serviceId: 's-wedding',
    serviceName: 'Wedding Photography',
    name: 'Signature Wedding',
    slug: 'signature-wedding',
    description: 'Paket terfavorit dengan liputan penuh Akad & Resepsi serta album eksklusif.',
    price: 14500000,
    duration: '10 Jam',
    photographerCount: 2,
    editedPhotos: '150 Foto Edited + Cinematic Slideshow',
    features: [
      '2 Main Photographers + 1 Assistant',
      'Full Day Coverage (s/d 10 Jam)',
      '150 Color Graded High-Res Photos',
      'All Raw Files Included',
      'Exclusive Album Flushmount 20x30 cm (20 Halaman)',
      '2 Frames Minimalist Wooden 40x60 cm',
      'Cinematic Highlight Video Slideshow',
    ],
    isPopular: true,
    isActive: true,
  },
  {
    id: 'pkg-w-luxury',
    serviceId: 's-wedding',
    serviceName: 'Wedding Photography',
    name: 'Royal Heritage Wedding',
    slug: 'royal-heritage',
    description: 'Pengalaman dokumentasi premium tanpa kompromi untuk perayaan agung.',
    price: 22000000,
    duration: 'Full Day / Unlimited',
    photographerCount: 3,
    editedPhotos: '250 Foto Edited + Printed Book + Video',
    features: [
      '3 Master Photographers',
      'Unlimited Full Day Coverage',
      '250 Premium Color Graded Photos',
      'Luxurious Leather Album 30x40 cm (30 Halaman)',
      '2 Mini Parent Albums 20x30 cm',
      '3 Frames Gallery Wall Wooden Canvas 50x75 cm',
      'Drone Aerial Photography (If Location Permits)',
      'Fast-track 48h Preview Edit (20 Photos)',
    ],
    isPopular: false,
    isActive: true,
  },

  // Pre-Wedding Packages
  {
    id: 'pkg-pw-classic',
    serviceId: 's-prewedding',
    serviceName: 'Pre-Wedding Story',
    name: 'Classic Session',
    slug: 'classic-prewedding',
    description: 'Sesi outdoor 1 lokasi dengan konsep natural & timeless.',
    price: 4500000,
    duration: '4 Jam',
    photographerCount: 1,
    editedPhotos: '35 Foto Edited',
    features: [
      '1 Photographer + 1 Lighting Assistant',
      '1 Outdoor / Studio Location',
      '2 Outfit Changes',
      '35 Edited High-Res Photos',
      '1 Canvas Frame 50x75 cm',
    ],
    isPopular: false,
    isActive: true,
  },
  {
    id: 'pkg-pw-editorial',
    serviceId: 's-prewedding',
    serviceName: 'Pre-Wedding Story',
    name: 'Editorial Vignette',
    slug: 'editorial-vignette',
    description: 'Sesi penuh gaya sinematik di 2-3 lokasi favorit Anda.',
    price: 7800000,
    duration: '8 Jam',
    photographerCount: 2,
    editedPhotos: '60 Foto Edited + Magazine Print',
    features: [
      '2 Lead Photographers',
      'Up to 3 Locations in City/Nature',
      '4 Outfit Changes',
      '60 Editorial Tone Edited Photos',
      'Custom Printed Coffee Table Book 20x25 cm',
      '2 Canvas Frames 50x75 cm with Premium Border',
      'All Master Files in Flashdrive',
    ],
    isPopular: true,
    isActive: true,
  },

  // Portrait / Couple / Graduation
  {
    id: 'pkg-portrait-solo',
    serviceId: 's-portrait',
    serviceName: 'Editorial & Portrait',
    name: 'Solo & Branding Portrait',
    slug: 'solo-portrait',
    description: 'Potret personal untuk profil profesional, artistik, atau personal branding.',
    price: 1800000,
    duration: '2 Jam',
    photographerCount: 1,
    editedPhotos: '15 Foto Edited',
    features: [
      '1 Photographer',
      'Studio or Indoor Location',
      '2 Outfits',
      '15 Retouched High-Res Photos',
      'Digital Delivery in 5 Days',
    ],
    isPopular: false,
    isActive: true,
  },
];

export const MOCK_PROJECTS: GalleryProject[] = [
  {
    id: 'proj-1',
    title: 'Warm Sanctuary of Arya & Nadia',
    slug: 'arya-nadia-wedding',
    category: 'wedding',
    categoryLabel: 'Wedding',
    description: 'Perayaan pernikahan intim bernuansa budaya modern yang hangat di Danau Toba & Madura.',
    location: 'Toba Heritage Resort, North Sumatra',
    eventDate: '12 Mei 2026',
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1600&auto=format&fit=crop',
    isFeatured: true,
    images: [
      {
        id: 'img-1-1',
        projectId: 'proj-1',
        imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1600&auto=format&fit=crop',
        altText: 'Arya & Nadia Wedding Couple Portrait',
        sortOrder: 1,
        aspectRatio: 'landscape',
      },
      {
        id: 'img-1-2',
        projectId: 'proj-1',
        imageUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1600&auto=format&fit=crop',
        altText: 'Emotional Vow Moment',
        sortOrder: 2,
        aspectRatio: 'portrait',
      },
      {
        id: 'img-1-3',
        projectId: 'proj-1',
        imageUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=1600&auto=format&fit=crop',
        altText: 'Bride Aesthetic Preparation',
        sortOrder: 3,
        aspectRatio: 'portrait',
      },
      {
        id: 'img-1-4',
        projectId: 'proj-1',
        imageUrl: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=1600&auto=format&fit=crop',
        altText: 'Evening Reception Glow',
        sortOrder: 4,
        aspectRatio: 'landscape',
      },
    ],
  },
  {
    id: 'proj-2',
    title: 'Poetry in Minimalist Light — Kevin & Clara',
    slug: 'kevin-clara-prewedding',
    category: 'pre-wedding',
    categoryLabel: 'Pre-Wedding',
    description: 'Sesi pre-wedding berkonsep arsitektural minimalis dengan fokus pada siluet dan kontras lembut.',
    location: 'Grand Ballroom & Modern Studio, Madura',
    eventDate: '28 April 2026',
    coverImage: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=1600&auto=format&fit=crop',
    isFeatured: true,
    images: [
      {
        id: 'img-2-1',
        projectId: 'proj-2',
        imageUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?q=80&w=1600&auto=format&fit=crop',
        altText: 'Kevin & Clara Studio Embrace',
        sortOrder: 1,
        aspectRatio: 'landscape',
      },
      {
        id: 'img-2-2',
        projectId: 'proj-2',
        imageUrl: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=1600&auto=format&fit=crop',
        altText: 'Sunset Contour',
        sortOrder: 2,
        aspectRatio: 'portrait',
      },
      {
        id: 'img-2-3',
        projectId: 'proj-2',
        imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1600&auto=format&fit=crop',
        altText: 'Close Up Emotional Detail',
        sortOrder: 3,
        aspectRatio: 'portrait',
      },
    ],
  },
  {
    id: 'proj-3',
    title: 'Reflections of Elegance — Sarah Persona',
    slug: 'sarah-persona-portrait',
    category: 'portrait',
    categoryLabel: 'Portrait',
    description: 'Eksplorasi estetika portrait editorial wanita dengan tone analog dramatis.',
    location: 'Sera Creative Studio, Madura',
    eventDate: '15 Maret 2026',
    coverImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1600&auto=format&fit=crop',
    isFeatured: true,
    images: [
      {
        id: 'img-3-1',
        projectId: 'proj-3',
        imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1600&auto=format&fit=crop',
        altText: 'Sarah Editorial Portrait',
        sortOrder: 1,
        aspectRatio: 'portrait',
      },
      {
        id: 'img-3-2',
        projectId: 'proj-3',
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1600&auto=format&fit=crop',
        altText: 'Moody Soft Shadow Portrait',
        sortOrder: 2,
        aspectRatio: 'portrait',
      },
    ],
  },
  {
    id: 'proj-4',
    title: 'The Eternal Oath of Bima & Dian',
    slug: 'bima-dian-wedding',
    category: 'wedding',
    categoryLabel: 'Wedding',
    description: 'Pernikahan outdoor bergaya garden rustic dengan sentuhan kehangatan keluarga.',
    location: 'Jalan pamekasan',
    eventDate: '02 Februari 2026',
    coverImage: 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?q=80&w=1600&auto=format&fit=crop',
    isFeatured: false,
    images: [
      {
        id: 'img-4-1',
        projectId: 'proj-4',
        imageUrl: 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?q=80&w=1600&auto=format&fit=crop',
        altText: 'Bima & Dian Ring Exchange',
        sortOrder: 1,
        aspectRatio: 'landscape',
      },
    ],
  },
];

// Sample availability data for August & September 2026
export const MOCK_AVAILABILITY: Availability[] = [
  {
    id: 'av-1',
    date: '2026-08-15',
    status: 'booked',
    notes: 'Wedding Bima & Dian (2 Slot Wedding Terisi Full)',
    weddingSlots: [
      { id: 'w1', name: 'Sesi 1 (Pagi / Siang)', startTime: '08:00', endTime: '14:00', timeRange: '08:00 - 14:00 WIB', isBooked: true, bookedBy: 'Bima & Dian' },
      { id: 'w2', name: 'Sesi 2 (Sore / Malam)', startTime: '15:00', endTime: '21:00', timeRange: '15:00 - 21:00 WIB', isBooked: true, bookedBy: 'Rian & Sarah' },
    ],
  },
  {
    id: 'av-2',
    date: '2026-08-16',
    status: 'blocked',
    notes: 'Internal Maintenance / Rest Day Studio',
  },
  {
    id: 'av-3',
    date: '2026-08-20',
    status: 'almost_full',
    notes: 'Sisa 1 Slot Wedding (Sesi Sore/Malam)',
    weddingSlots: [
      { id: 'w1', name: 'Sesi 1 (Pagi / Siang)', startTime: '08:00', endTime: '14:00', timeRange: '08:00 - 14:00 WIB', isBooked: true, bookedBy: 'Farih & Nita' },
      { id: 'w2', name: 'Sesi 2 (Sore / Malam)', startTime: '15:00', endTime: '21:00', timeRange: '15:00 - 21:00 WIB', isBooked: false },
    ],
    bookedTimeSlots: [
      { customerName: 'Farih Setiawan', startTime: '08:00', endTime: '14:00', serviceCategory: 'Wedding Package Signature', bookingCode: 'MS-260820-009' }
    ]
  },
  {
    id: 'av-4',
    date: '2026-08-22',
    status: 'booked',
    notes: 'Sesi Pre-Wedding Outdoor Full Day',
    bookedTimeSlots: [
      { customerName: 'Abroril Huda', startTime: '10:00', endTime: '18:00', serviceCategory: 'Pre-Wedding Cinematic', bookingCode: 'MS-260822-011' },
      { customerName: 'Deni Kurniawan', startTime: '19:00', endTime: '21:00', serviceCategory: 'Portrait Studio', bookingCode: 'MS-260822-015' }
    ]
  },
  {
    id: 'av-5',
    date: '2026-08-23',
    status: 'booked',
    notes: 'Full Day Corporate Event Coverage',
    bookedTimeSlots: [
      { customerName: 'Budi Santoso', startTime: '08:00', endTime: '17:00', serviceCategory: 'Commercial Event', bookingCode: 'MS-260823-014' }
    ]
  },
  {
    id: 'av-6',
    date: '2026-08-28',
    status: 'almost_full',
    notes: '1 Slot Wedding Pagi Tersedia & Sesi Graduation Terisi',
    weddingSlots: [
      { id: 'w1', name: 'Sesi 1 (Pagi / Siang)', startTime: '08:00', endTime: '14:00', timeRange: '08:00 - 14:00 WIB', isBooked: false },
      { id: 'w2', name: 'Sesi 2 (Sore / Malam)', startTime: '15:00', endTime: '21:00', timeRange: '15:00 - 21:00 WIB', isBooked: true, bookedBy: 'Aldo & Maya' },
    ],
    bookedTimeSlots: [
      { customerName: 'Aldo Pratama', startTime: '15:00', endTime: '21:00', serviceCategory: 'Wedding Deluxe', bookingCode: 'MS-260828-005' },
      { customerName: 'Siti Rahma', startTime: '09:00', endTime: '11:00', serviceCategory: 'Graduation Package', bookingCode: 'MS-260828-012' }
    ]
  },
  {
    id: 'av-7',
    date: '2026-08-29',
    status: 'almost_full',
    notes: 'Sesi Pagi Wedding Terisi, Sesi Sore Tersedia',
    weddingSlots: [
      { id: 'w1', name: 'Sesi 1 (Pagi / Siang)', startTime: '08:00', endTime: '14:00', timeRange: '08:00 - 14:00 WIB', isBooked: true, bookedBy: 'Ahmad Rizky' },
      { id: 'w2', name: 'Sesi 2 (Sore / Malam)', startTime: '15:00', endTime: '21:00', timeRange: '15:00 - 21:00 WIB', isBooked: false },
    ],
  },
  {
    id: 'av-8',
    date: '2026-09-05',
    status: 'blocked',
    notes: 'Outside Madura Project',
  },
  {
    id: 'av-9',
    date: '2026-09-12',
    status: 'almost_full',
    notes: 'Couple Session Afternoon Booked (13:00 - 17:00)',
    bookedTimeSlots: [
      { customerName: 'Rian Hidayat', startTime: '13:00', endTime: '17:00', serviceCategory: 'Couple Portrait', bookingCode: 'MS-260912-003' }
    ]
  },
];

export const MOCK_BANK_ACCOUNTS = [
  { bankName: 'Bank BCA', accountNumber: '188-091-2345', accountHolder: 'Marga Sera Photography (Abroril Huda)' },
  { bankName: 'Bank Mandiri', accountNumber: '140-00-1928374-1', accountHolder: 'Abroril Huda' },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b-1',
    bookingCode: 'MS-260829-001',
    customerName: 'Ahmad Rizky',
    whatsapp: '081234567890',
    email: 'ahmad.rizky@example.com',
    instagram: '@ahmad.rizky',
    serviceId: 's-wedding',
    serviceName: 'Wedding Photography',
    packageId: 'pkg-w-signature',
    packageName: 'Signature Wedding',
    bookingDate: '2026-08-29',
    startTime: '08:00',
    endTime: '14:00',
    slotType: 'wedding_morning',
    location: 'Bangkalan, Madura',
    eventType: 'Akad & Resepsi Pernikahan',
    notes: 'Mohon fokus pada reaksi orang tua dan momen penyerahan mahar.',
    status: 'confirmed',
    paymentStatus: 'dp_paid',
    downPayment: 4350000,
    paidAmount: 4350000,
    remainingAmount: 10150000,
    totalPrice: 14500000,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'b-2',
    bookingCode: 'MS-260915-002',
    customerName: 'Priscillia & Daniel',
    whatsapp: '081987654321',
    email: 'priscillia@example.com',
    instagram: '@priscillia.d',
    serviceId: 's-prewedding',
    serviceName: 'Pre-Wedding Story',
    packageId: 'pkg-pw-editorial',
    packageName: 'Editorial Vignette',
    bookingDate: '2026-09-15',
    startTime: '13:00',
    endTime: '21:00',
    slotType: 'custom',
    location: 'Berastagi & Heritage District',
    eventType: 'Pre-Wedding Outdoor',
    notes: 'Konsep pakaian serba hitam & warna vintage pastel.',
    status: 'pending',
    paymentStatus: 'unpaid',
    downPayment: 2340000,
    paidAmount: 0,
    remainingAmount: 7800000,
    totalPrice: 7800000,
    createdAt: '2026-08-10T14:30:00Z',
  },
];
